dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

env:
  DEP_VERSION="0.3.2"

before_install:
  - eval "$(GIMME_GO_VERSION=1.8.3 gimme)"
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

  # Install golang/dep (https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-use-dep-in-ci)  
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install: true

script:
  # Unit-test and build server
  - cd server/
  - ./gradlew build --info
  - cd ..

  # Unit-test and build integration server
  - cd github-integration/
  - ./gradlew build --info
  - cd ..

  # Launch local zally server
  - cd server/
  - ./gradlew bootRun > /dev/null &
  - echo $! > /tmp/zally_server.pid
  - cd ..

  # Wait until Spring Boot will start
  - while ! echo "GET / HTTP/1.0\n" | nc localhost 8080; do sleep 1; done

  # Test and build CLI
  - export ZALLY_GO_PATH="$GOPATH/src/github.com/zalando/zally"
  - mkdir -p $ZALLY_GO_PATH
  - cp -R . $ZALLY_GO_PATH
  - cd $ZALLY_GO_PATH/cli/zally
  - dep ensure
  - ./test.sh integration
  - go build
  - cd $TRAVIS_BUILD_DIR

  # Kill Zally server instace
  - kill -9 `cat /tmp/zally_server.pid`

  # Unit-test web UI
  - cd web-ui
  - node --version
  - npm --version
  - yarn --version
  - yarn install -q
  - yarn test
  - yarn build
  - cd $TRAVIS_BUILD_DIR

after_success:
  # Upload test code coverage report for Zally server to codacy
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r server/build/reports/jacoco/test/jacocoTestReport.xml
  # Upload test code coverage report for Zally server to codecov
  - bash <(curl -s https://codecov.io/bash) -f server/build/reports/jacoco/test/jacocoTestReport.xml
  # Upload test code coverage report for Zally integration server
  - bash <(curl -s https://codecov.io/bash) -f github-integration/build/reports/jacoco/test/jacocoTestReport.xml
  # Upload test code coverage report for Zally CLI
  - bash <(curl -s https://codecov.io/bash) -f $ZALLY_GO_PATH/cli/zally/coverage.txt -f $TRAVIS_BUILD_DIR/web-ui/target/coverage/lcov.info
