endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
    sensitive: false

spring:
  datasource:
    url: jdbc:hsqldb:mem:storage;sql.syntax_pgs=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate

security:
  basic:
    enabled: false

management.port: 0

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-api.yaml"

zally:
  scanPackages: com.corefiling.zally
  apiGuidelinesBaseUrl: "http://zalando.github.io/restful-api-guidelines"
  cli:
    releasesPage: https://github.com/zalando-incubator/zally/releases
    deprecatedCliAgents: unirest-java/1.3.11,Zally-CLI/1.0