endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
    sensitive: false

spring:
  datasource:
    url: jdbc:hsqldb:mem:storage;sql.syntax_pgs=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate

security:
  basic:
    enabled: false

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-api.yaml"

management.port: 8080

zally:
  scanPackages: com.corefiling.zally
  cli:
    releasesPage: https://github.com/zalando/zally/releases
    deprecatedCliAgents: unirest-java/1.3.11,Zally-CLI/1.0
