spring:
  profiles:
    active: production
  datasource:
    url: jdbc:hsqldb:mem:storage;sql.syntax_pgs=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            # Disable noisy detection for LOB support (Postgres doesn't support it anyway)
            # Workaround from https://hibernate.atlassian.net/browse/HHH-12368
            # Should be unnecessary after upgrading to Spring Boot 2.2.0
            non_contextual_creation: true
  oauth2:
    resource:
      tokenInfoUri: ${TOKEN_INFO_URI}

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /
      exposure:
        include: health, metrics
  server:
    port: ${MANAGEMENT_PORT:7979}

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-api.yaml"

rules-config-path: "rules-config.conf"

zally:
  # rules to be ignored system wide by default
  ignoreRules: M008, M009, M010, M011, H001, H002, S005, S006, S007
  cli:
    releasesPage: https://github.com/zalando/zally/releases
    deprecatedCliAgents: unirest-java/1.3.11,Zally-CLI/1.0
---
spring.profiles: local
TOKEN_INFO_URI: https://auth.example.com/oauth2/tokeninfo
